name: Latest Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  test_minimal_app:
    name: Test Minimal Application with Base Dependencies
    runs-on: ubuntu-latest
    env:
      python_version: "3.12"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: pdm-project/setup-pdm@v3
        name: Set up PDM
        with:
          python-version: "3.12"
          allow-python-prereleases: false
          cache: true
          cache-dependency-path: |
            ./pdm.lock

      - name: Install dependencies
        run: pdm install

      - name: Set pythonpath
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV

      - name: Test
        run: mv tests/examples/test_hello_world.py test_hello_world.py && pdm run pytest test_hello_world.py

  publish-release:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: release
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: pdm-project/setup-pdm@v3
        name: Set up PDM
        with:
          python-version: "3.12"
          cache: true

      - name: Build package
        run: pdm build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
